from GRAPHICS import rectangle,circle,cuboid,sphere
l=int(input("ENTER THE LENGTH OF RECTANGLE"))
b=int(input("ENTER THE BREADTH OF RECTANGLE"))
rectangle.area(l,b)
rectangle.perimeter(l,b)
r=int(input("ENTER THE RADIUS CIRCLE"))
circle.area(r)
circle.perimeter(r)
l=int(input("ENTER THE LENGTH OF CUBOID"))
b=int(input("ENTER THE BREADTH OF CUBOID"))
h=int(input("ENTER THE HEIGHT OF CUBOID"))
cuboid.area(l,b,h)
cuboid.perimeter(l,b,h)
r=int(input("ENTER THE RADIUS OF SPHERE"))
sphere.area(r)
sphere.perimeter(r)